
    services:
      # Backend Service
      - type: web
        name: safeguard-ai-backend
        env: node
        rootDir: backend
        buildCommand: npm install
        startCommand: npm start
        healthCheckPath: /health

      # Frontend Static Site
      - type: static
        name: safeguard-ai-frontend
        buildCommand: npm install && npm run build
        staticPublishPath: dist
